"""system sync

Revision ID: 0d6a01a7ebd6
Revises: ae8e316fa1da
Create Date: 2026-06-05 10:48:32.342850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6a01a7ebd6'
down_revision: Union[str, Sequence[str], None] = 'ae8e316fa1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('purpose', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_password_reset_tokens_purpose'), 'password_reset_tokens', ['purpose'], unique=False)
    op.add_column('students', sa.Column('email_verified', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email_verified')
    op.drop_index(op.f('ix_password_reset_tokens_purpose'), table_name='password_reset_tokens')
    op.drop_column('password_reset_tokens', 'purpose')
    # ### end Alembic commands ###
