"""system sync

Revision ID: 206ccd6fd444
Revises: 13c9e28963f7
Create Date: 2026-05-30 11:06:53.695690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206ccd6fd444'
down_revision: Union[str, Sequence[str], None] = '13c9e28963f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_events', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_events', 'status')
    # ### end Alembic commands ###
