"""system sync

Revision ID: 90e796b8215a
Revises: 9bf2dbcbafaf
Create Date: 2026-06-08 09:19:03.795397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e796b8215a'
down_revision: Union[str, Sequence[str], None] = '9bf2dbcbafaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email_verified', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
