"""system sync

Revision ID: d697c9245f91
Revises: 11c062f7ff4c
Create Date: 2026-05-31 22:44:06.013208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd697c9245f91'
down_revision: Union[str, Sequence[str], None] = '11c062f7ff4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_class_attendance_class_student', 'class_attendance', ['class_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_class_attendance_class_student', 'class_attendance', type_='unique')
    # ### end Alembic commands ###
